Fixed test suite to work with Solaris Bourne shell: 1) Removed ! (negation) of statuses. 2) Removed initializations from export statements. 3) Replaced $() with ``. 4) Replaced $(()) (and expr) with new function arith_eval (). (cherry picked from commit a6af3b6300e02ade9f223f8d91667f590d191dc9)

diff --git a/test/mhparam/test-mhparam b/test/mhparam/test-mhparam
--- a/test/mhparam/test-mhparam
+++ b/test/mhparam/test-mhparam
@@ -31,13 +31,16 @@ Usage: mhparam [profile-components] [switches]
   -version
   -help
 EOF
-# The exit status is 1 with -help, so invert it to prevent
-# triggering immediate exit due to set -e.
-! mhparam -help >$actual 2>&1
+# The exit status is 1 with -help, so temporarily disable -e.
+set +e
+mhparam -help >$actual 2>&1
+set -e
 check $expected $actual
 
 # check -version
-if ! mhparam -v | grep '^mhparam --' >/dev/null; then
+if mhparam -v | grep '^mhparam --' >/dev/null; then
+  :
+else
   echo "$0: mhparam -v generated unexpected output" 1>&2
   failed=`expr ${failed:-0} + 1`
 fi
@@ -133,8 +136,10 @@ check $expected $actual
 run_test 'mhparam faceproc formatproc rmmproc' ''
 
 #### test sbackup separately because it's only passed as a -D compile option
-if ! mhparam sbackup | grep -F ',
+if mhparam sbackup | grep -F ',
 #' >/dev/null; then
+  :
+else
   echo mhparam sbackup failed
   failed=`expr ${failed:-0} + 1`
 fi
diff --git a/test/mhpath/test-mhpath b/test/mhpath/test-mhpath
--- a/test/mhpath/test-mhpath
+++ b/test/mhpath/test-mhpath
@@ -27,13 +27,16 @@ Usage: mhpath [+folder] [msgs] [switches]
   -version
   -help
 EOF
-# The exit status is 1 with -help, so invert it to prevent
-# triggering immediate exit due to set -e.
-! mhpath -help > $actual 2>&1
+# The exit status is 1 with -help, so temporarily disable -e.
+set +e
+mhpath -help > $actual 2>&1
+set -e
 check $expected $actual
 
 # check -version
-if ! mhpath -v | grep '^mhpath --' > /dev/null; then
+if mhpath -v | grep '^mhpath --' > /dev/null; then
+  :
+else
   echo "$0: mhpath -v generated unexpected output" 1>&2
   failed=`expr ${failed:-0} + 1`
 fi
