Generalized condition for support of parameter value tests.

diff --git a/test/mhshow/test-charset b/test/mhshow/test-charset
--- a/test/mhshow/test-charset
+++ b/test/mhshow/test-charset
@@ -25,11 +25,11 @@ if test "$ICONV_ENABLED" -eq 0; then
     text_size=10
 else
     text_size=11
-    if ! iconv -l | grep EBCDIC-US >/dev/null; then
-        #### For unknown reasons, the parameter values checks
-        #### fail on the FreeBSD10 buildbot.  It doesn't
-        #### support EBCDIC-US, which is used by the checks,
-        #### so use that to detect whether to skip the check.
+    if ! printf '\xe4' | iconv -f EBCDIC-US -t UTF-8 >/dev/null 2>&1; then
+        #### For unknown reasons, the parameter values checks fail on the
+        #### FreeBSD10 buildbot.  It doesn't support EBCDIC-US, which is used
+        #### by the checks, so check for that.  Though that doesn't seem to be
+        #### the reason.
         skip_param_value_checks=1
     fi
 fi
